version: '3.4'

services:
  counterparts-api:
    image: mysql:8.0.22
    container_name: counterparts-api
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: counterparts-api
    ports:
      - "3389:3306"